### ISSUE TITLE
V0.0.2 crash on Android 14

### ISSUE THREAD

**Issue by dreawer** [wh201906/SerialPipe#2]
Version 0.0.2 (from F-Droid) crashes immediately after launch. V0.0.1 (from github) launches without issues.
Device: Xiaomi 13/MIUI 14/Android 14

**Comment by wh201906** [comment]
Yes the release build is broken on all platforms due to the missing ProGuard rule.
To fix this bug I've created v0.0.3 and requested an update on F-Droid. The new version will be available in the next few days.

**Comment by wh201906** [comment]
You can download the new version there.
https://github.com/wh201906/SerialPipe/releases/tag/v0.0.3
